language: java
jdk:
  - openjdk10
services:
  - docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

jobs:
  include:
    - stage: build
      script: ./gradlew assemble
    - stage: test
      script:
        - ./gradlew check
        -  bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      if: branch IN (master, dev)
      script:
        - ./gradlew publish
        - bash ./scripts/docker_deploy.sh

notifications:
  slack: exaucetsiege:Tjeo1DuAEFQcwCovonR965F6