language: java
jdk:
  - openjdk10
services:
  - docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - chmod +x ./gradlew
  
jobs:
  include:
    - stage: build
      script: ./gradlew assemble
    - stage: test
      script:
        - ./gradlew check
        -  bash <(curl -s https://codecov.io/bash)
